### ISSUE TITLE
Fb DO NOT sync products with woocommerce

### ISSUE THREAD

**Issue by carlaochoa** [facebook/facebook-for-woocommerce#2101]
Everytime I add a new product in Woocommerce it DOES NOT SYNC with Facebook so I'm not able to tag any product in my posts or anywhere. PLEASE, I NEED HELP. IT IS URGENT!!!!!

**Comment by budzanowski** [comment]
Please check Qustions and Support section of https://docs.woocommerce.com/document/how-to-get-help/#questions-and-support to find how to get help with your problem.
