### ISSUE TITLE
Products remain on Facebook when set to draft

### ISSUE THREAD

**Issue by sukafia** [facebook/facebook-for-woocommerce#2547]
## ✍️ Describe the bug

Typically, when you publish a product it's synced to Facebook. When you set the same product to private or hidden, it's removed from Facebook. However, unlike when hidden and set to private, products remain on Facebook when set to draft. 

## 🚶‍♀️ Steps to reproduce

1. Sync products to Facebook as usual
2. Set the product to draft
3. Notice the product remains on Facebook while the Facebook sync widget returns "Product is not published"

![wKHDgA.png](https://github.com/woocommerce/facebook-for-woocommerce/assets/60121732/c5df8da1-01c2-4a0a-aba5-e8f2a12e87dc)

## ✔️ Expected behavior

Published products should be removed from Facebook once set to draft

**Comment by sukafia** [comment]
6300792-zen

**Comment by H4ldrz** [comment]
Has it been fixed?

3.0.24 – 2023-06-06

Fix – Product variants weren’t deleted correctly from the Facebook catalog in some instances.

**Comment by Archie22is** [comment]
I think that will work. I'm in the same boat at well... Definitely an upvote

**Comment by Archie22is** [comment]
Not to hijack @sukafia's ticket, but @H4ldrz yes, the bug is still there, I thought the update would resolve the bug but it didn't.
