### ISSUE TITLE
Missing purchase event in catalog manager

### ISSUE THREAD

**Issue by lojj35** [facebook/facebook-for-woocommerce#438]
Hi,
The facebook for woocommerce plugin is installed, I have added my product catalog to Facebook. Facebook says it is tracking events via the pixel. But I have some issues/errors: 
When I look at my site using the pixel helper it says - "can't match products"
The Facebook catalog shows the following errors -
1. google_product_category field is missing on all products in the catalog 
2. Missing add to cart & purchase events in web pixel (when I check this using the pixel helper it says it correctly recorded the add to cart event) 
I would really love some help as I have no idea how to fix this issue.  Is there another plugin that would help me resolve this? 
the website is https://matcha-and-ink.com 
Thank you :)

**Comment by sammul** [comment]
@lojj35 We fixed this issue in v1.8.5. 
https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.5
Can you try and let us know if it can be fixed?

**Comment by lojj35** [comment]
Hi,

I have installed version 1.8.5 & I still have the same two catalog errors, one says its missing purchase events

& other issue says its not getting google product category events.  Also when I look at the pixel analytics it says it doesn’t seem to be able to pick up purchase conversions 

I have included screenshots below

Thanks :)

**Comment by mengyingdu** [comment]
Hi @lojj35 ,

1. google product category errors: similar to #402 

You can ignore this error, it's harmless.

Here's what it means though:

If you have a per-product attribute called google_product_category which correspond's to an entry in google's product taxonomy, we can potentially import that (Google set the standard for this). It helps the accuracy of FB product classification, which in turn helps us recommend correct products in ads when appropriate. (e.g. Someone buys a shoe, we can recommend them a sock, if we have a correct classification.) However, our classification algorithms are already fairly accurate even without this information, so it helps but it's not essential.

2. missing purchase events but pixel helper shows fired

We have seen reports that the event manager shows missing events but they have been actually fired and can be confirmed by pixel helper. It's not a bug for the plugin if you can confirmed with your pixel helper. @dmitridr Do you think it as sth wrong on catalog manager side?
